title: ANZCO Foods Ltd systems status page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Website
      description: Our company public facing website
      link: https://anzcofoods.com/
    - name: Helpdesk
      description: Our IT support site
      link: http://anzco-vfire01.cmp.local/vfire/Core.aspx?Lite
    - name: Wireless Network
      description: ANZCO Wireless Networks
    - name: Wired Network
    - name: Email
      description: ANZCO Email Systems
    - name: Microsoft Teams
      link: https://teams.microsoft.com/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: Pacific/Auckland
  logo: /images/clearstatus.svg
  description_header: ""
  copyrightHolder: ANZCO Foods Ltd.
  eventsPerPage: 10
  iconType: image/png
  groups:
    - ANZCO
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit anzcofoods.com/'
    href='https://anzcofoods.com/'>anzcofoods.com</a>.
